stages:
    - format

format:check:
    stage: format
    image: node:22
    before_script:
        - yarn install --frozen-lockfile
    script:
        - yarn run format:check
    only:
        - merge_requests
